version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prueba_tecnica_b4
      - SPRING_DATASOURCE_USERNAME=prueba_user
      - SPRING_DATASOURCE_PASSWORD=prueba_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prueba_tecnica_b4
      - POSTGRES_USER=prueba_user
      - POSTGRES_PASSWORD=prueba_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: